// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PegauchoBackend.Data;

#nullable disable

namespace PegauchoBackend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251013224237_addproduc")]
    partial class addproduc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Orders.Shared.Entities.Usuario", b =>
                {
                    b.Property<int>("idLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLogin"));

                    b.Property<string>("contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idLogin");

                    b.HasIndex("usuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Pegaucho.Shared.Entities.Produccion", b =>
                {
                    b.Property<int>("idOrdenProd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idOrdenProd"));

                    b.Property<int>("UsuarioidLogin")
                        .HasColumnType("int");

                    b.Property<double>("cantidadLitros")
                        .HasColumnType("float");

                    b.Property<int>("codProd")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("idLogin")
                        .HasColumnType("int");

                    b.Property<string>("maquinaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("matPrima")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prioridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idOrdenProd");

                    b.HasIndex("UsuarioidLogin");

                    b.HasIndex("idOrdenProd")
                        .IsUnique();

                    b.ToTable("Producciones");
                });

            modelBuilder.Entity("Pegaucho.Shared.Entities.Produccion", b =>
                {
                    b.HasOne("Orders.Shared.Entities.Usuario", "Usuario")
                        .WithMany("Producciones")
                        .HasForeignKey("UsuarioidLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Orders.Shared.Entities.Usuario", b =>
                {
                    b.Navigation("Producciones");
                });
#pragma warning restore 612, 618
        }
    }
}
