// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PegauchoBackend.Data;

#nullable disable

namespace PegauchoBackend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251014061548_InitialCreated")]
    partial class InitialCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Orders.Shared.Entities.Usuario", b =>
                {
                    b.Property<int>("IdLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLogin"));

                    b.Property<string>("contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdLogin");

                    b.HasIndex("usuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Pegaucho.Shared.Entities.OrdenDosificacion", b =>
                {
                    b.Property<int>("IdOrdenDos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrdenDos"));

                    b.Property<int>("IdOrdenPanel")
                        .HasColumnType("int");

                    b.Property<int>("IdOrdenProd")
                        .HasColumnType("int");

                    b.Property<int?>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("codProd")
                        .HasColumnType("int");

                    b.Property<decimal?>("costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("maquinaProd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("matPrima")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prioridad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("tiempoEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdOrdenDos");

                    b.HasIndex("IdOrdenDos")
                        .IsUnique();

                    b.HasIndex("IdOrdenPanel");

                    b.HasIndex("IdOrdenProd");

                    b.ToTable("OrdenesDosificacion");
                });

            modelBuilder.Entity("Pegaucho.Shared.Entities.OrdenProduccion", b =>
                {
                    b.Property<int>("IdOrdenProd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrdenProd"));

                    b.Property<int>("IdLogin")
                        .HasColumnType("int");

                    b.Property<int>("IdOrdenPanel")
                        .HasColumnType("int");

                    b.Property<int?>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("codProd")
                        .HasColumnType("int");

                    b.Property<decimal?>("costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("maquinaProd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("matPrima")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prioridad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("tiempoEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdOrdenProd");

                    b.HasIndex("IdLogin");

                    b.HasIndex("IdOrdenPanel");

                    b.HasIndex("IdOrdenProd")
                        .IsUnique();

                    b.ToTable("OrdenesProduccion");
                });

            modelBuilder.Entity("Pegaucho.Shared.Entities.PanelControl", b =>
                {
                    b.Property<int>("IdOrdenPanel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrdenPanel"));

                    b.Property<int>("IdLogin")
                        .HasColumnType("int");

                    b.HasKey("IdOrdenPanel");

                    b.HasIndex("IdLogin");

                    b.HasIndex("IdOrdenPanel")
                        .IsUnique();

                    b.ToTable("PanelesControl");
                });

            modelBuilder.Entity("Pegaucho.Shared.Entities.OrdenDosificacion", b =>
                {
                    b.HasOne("Pegaucho.Shared.Entities.PanelControl", "PanelControl")
                        .WithMany("OrdenesDosificaciones")
                        .HasForeignKey("IdOrdenPanel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pegaucho.Shared.Entities.OrdenProduccion", "OrdenProduccion")
                        .WithMany("OrdenesDosificaciones")
                        .HasForeignKey("IdOrdenProd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenProduccion");

                    b.Navigation("PanelControl");
                });

            modelBuilder.Entity("Pegaucho.Shared.Entities.OrdenProduccion", b =>
                {
                    b.HasOne("Orders.Shared.Entities.Usuario", "Usuario")
                        .WithMany("OrdenesProducciones")
                        .HasForeignKey("IdLogin")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pegaucho.Shared.Entities.PanelControl", "PanelControl")
                        .WithMany("OrdenesProduccion")
                        .HasForeignKey("IdOrdenPanel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PanelControl");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Pegaucho.Shared.Entities.PanelControl", b =>
                {
                    b.HasOne("Orders.Shared.Entities.Usuario", "Usuario")
                        .WithMany("Paneles")
                        .HasForeignKey("IdLogin")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Orders.Shared.Entities.Usuario", b =>
                {
                    b.Navigation("OrdenesProducciones");

                    b.Navigation("Paneles");
                });

            modelBuilder.Entity("Pegaucho.Shared.Entities.OrdenProduccion", b =>
                {
                    b.Navigation("OrdenesDosificaciones");
                });

            modelBuilder.Entity("Pegaucho.Shared.Entities.PanelControl", b =>
                {
                    b.Navigation("OrdenesDosificaciones");

                    b.Navigation("OrdenesProduccion");
                });
#pragma warning restore 612, 618
        }
    }
}
